CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL
);

CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_id INTEGER,
    CONSTRAINT fk_folder
        FOREIGN KEY(folder_id)
            REFERENCES noteful_folders(id),
    note_name TEXT NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    content TEXT NOT NULL
);